### ISSUE TITLE
Dependencies and versions

### ISSUE THREAD

**Issue by gip** [mrnumber/ocaml-redis#6]
Would be cool to specify the known versions of Ocaml and Batteries used produce a successful build in the doc. Or at lest the version used for development. 
I've been trying with Ocaml 4.0.1 and different Batteries version with no luck so far. Few references points would be helpful :)

Thanks
Gilles

**Comment by rdegnan** [comment]
Hi Gilles,

I had built it successfully using Ocaml 3.12.1 and 4.0.1 and Batteries from the v2 and master branches on github. I just tried to compile with Batteries v1 and found some issues which are now fixed -- could you pull my changes and try again?

-Ryland
